### ISSUE TITLE
docker启动不起来

### ISSUE THREAD

**Issue by Lao-66** [libaibaia/cloudSec#2]
用的下面的新的yaml
registry.cn-hangzhou.aliyuncs.com/lx_project/cloud:vue-app-latest

没有任何报错。docker容器状态都是exited。只有db一直在restarting

**Comment by libaibaia** [comment]
贴一下容器日志。我现在没办法判断什么原因，有可能是docker版本的问题，因为前端配置文件有问题也不会导致一直重启的

**Comment by Lao-66** [comment]
java-app    | exec /usr/local/jdk1.8.0_351/bin/java: exec format error
db          | exec /usr/local/bin/docker-entrypoint.sh: exec format error
db          | exec /usr/local/bin/docker-entrypoint.sh: exec format error
db          | exec /usr/local/bin/docker-entrypoint.sh: exec format error
db          | exec /usr/local/bin/docker-entrypoint.sh: exec format error
db          | exec /usr/local/bin/docker-entrypoint.sh: exec format error
vue-web     | exec /docker-entrypoint.sh: exec format error


Docker version 24.0.2, build cb74dfc
docker-compose version 1.29.2, build unknown

**Comment by libaibaia** [comment]
刚刚重新更新了下镜像，你可以再试试，如果还不行先换个环境试一下，，ubuntu或者centos

**Comment by libaibaia** [comment]
我本地没办法复现你的问题，那你就按照本地部署的方式打包成docker镜像试一下

> 不行哦。我删除了镜像重新拉的新镜像还是起不来。我的系统就是ubuntu 22.04。
