### ISSUE TITLE
实例重复问题

### ISSUE THREAD

**Issue by Mayter** [libaibaia/cloudSec#3]
我不知道是个个人原因还是原有Bug，会有很多重复的机器，可以根据实例id去重嘛
![demo](https://github.com/libaibaia/cloudSec/assets/6148807/afa8c8f0-40f9-4432-a5d3-6454f6782d5c)

**Comment by libaibaia** [comment]
> 我不知道是个个人原因还是原有Bug，会有很多重复的机器，可以根据实例id去重嘛 ![演示](https://user-images.githubusercontent.com/6148807/245864694-afa8c8f0-40f9-4432-a5d3-6454f6782d5c.png)

aws的吗，另外这个是重新检测还是直接开始检测的

**Comment by Mayter** [comment]
> > 我不知道是个人原因还是原来有Bug，会有很多重复的机器，可以根据实例id去重嘛![表演](https://user-images.githubusercontent.com/6148807/245864694-afa8c8f0-40f9-4432-a5d3-6454f6782d5c.png)
> 
> aws的吗，另外这个是重新测试还是直接开始测试的

是直接导入的阿里云的ak，具体原因不知道，改天我可以在测试下

**Comment by libaibaia** [comment]
> > > 我不知道是个人原因还是原来有Bug，会有很多重复的机器，可以根据实例id去重嘛![表演](https://user-images.githubusercontent.com/6148807/245864694-afa8c8f0-40f9-4432-a5d3-6454f6782d5c.png)
> > 
> > 
> > aws的吗，另外这个是重新测试还是直接开始测试的
> 
> 是直接导入的阿里云的ak，具体原因不知道，改天我可以在测试下
原来有这个Key嘛，按道理是不会重复的，因为是遍历的每个区域

**Comment by Mayter** [comment]
我重新测试了下好像没这个问题了，非常抱歉
