### ISSUE TITLE
登陆时出现网关错误

### ISSUE THREAD

**Issue by ruisika** [libaibaia/cloudSec#7]
![image](https://github.com/libaibaia/cloudSec/assets/87137234/979d18d3-07bf-4df4-8e22-f9f92c72aabe)

使用国外vpn docker搭建 登陆时出现网关错误

**Comment by libaibaia** [comment]
后端容器没起来，可以稍等一会看看，如果还是502的话麻烦截图，docker ps

**Comment by ruisika** [comment]
> 

刚刚又试了一下修改为80就可以登录了 之前改的其他端口就会出现网关错误
